#!/bin/bash
# REQUIRED_PYTHON_VERSION="3"
# REQUIRED_PIP_VERSION="3"

################################################################################
## Checks if user is running as root
################################################################################
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

################################################################################
## Checks if Python is installed on the device and if installed, whether its
## version meets the requirement.
################################################################################
# {
#     ## Python reports the version to STDERR, so have to redirect STDERR to
#     ## STDOUT and not capture the output in a variable.
#     python$REQUIRED_PYTHON_VERSION --version >/dev/null 2>&1
# } || {
#     echo "Python $REQUIRED_PYTHON_VERSION" "Not found"
#     exit 1
# }

################################################################################
## Checks if pip is installed on the device and if installed, whether its
## version meets the requirement.
################################################################################
# {
#     ## Pip3 reports the version to STDERR, so have to redirect STDERR to
#     ## STDOUT and not capture the output in a variable.
#     pip$REQUIRED_PIP_VERSION --version >/dev/null 2>&1
# } || {
#     echo "Pip3" "Not found"
#     exit 1
# }

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 145B43408AB413B3

add-apt-repository ppa:telred/ppa

apt-get update

echo “deb http://ppa.launchpad.net/telred/ppa/ubuntu focal main” | sudo tee -a /etc/apt/sources.list

echo “deb-src http://ppa.launchpad.net/telred/ppa/ubuntu focal main ” | sudo tee -a /etc/apt/sources.list

apt-get install twain

cp /twain/service/twain.service /lib/systemd/system/
sed -i "s/<DEVICE_CODE>/$1/g" /twain/config/config.json

chmod 644 /lib/systemd/system/twain.service

systemctl daemon-reload

systemctl enable twain.service

systemctl start twain.service

